version: "3.9"
services:
  selenium_claro_drive_i0001:
    build: .
    image: selenium_claro_drive_i0001:latest
    ports:
      - "7900:7900"
    volumes:
      - ./screenshots:/screenshots
      - /etc/localtime:/etc/localtime:ro
    shm_size: '2gb'